services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - RECEIPT_PARSER_URL=http://receipt_parser:8001
    depends_on:
      - receipt_parser

  receipt_parser:
    build: ./receipt_parser
    ports:
      - "8001:8001"

  frontend:
    build: ./frontend
    ports:
      - "8501:80"
    depends_on:
      - backend
